version: '3.4'

services:
  local_postgres:
    image: postgres:latest
    restart: always
    ports:
      - '5432:5432'
    restart: always
    volumes:
      - db_volume:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'P@123'
    networks:
      - libraryapp-dev

  libraryapp.api:
    image: ${DOCKER_REGISTRY-}libraryappapi
    depends_on:
      - 'local_postgres'
    build:
      context: .
      dockerfile: LibraryApp.API/Dockerfile
    ports:
      - '3000:80'
    environment:
        'ConnectionStrings__LibraryConnection': "host=local_postgres;port=5432;database=LibraryTestDb;username=postgres;password=P@123;Pooling=true;"
    networks:
      libraryapp-dev:

volumes:
  db_volume:

networks:
  libraryapp-dev:
    driver: bridge
